/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion2_lab8;

import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KATHERINE
 */
public class Principal extends javax.swing.JFrame {
 DefaultTableModel modelo=new DefaultTableModel();
  DefaultTableModel modelo2=new DefaultTableModel();
   
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        logout.setVisible(false);
         modelo.addColumn("cantidad");
        modelo.addColumn("nombre");
        modelo.addColumn("precio");
        modelo.addColumn("fecha");;
        jt_tabla_productos.setModel(modelo);
        
        modelo2.addColumn("nombre");
        modelo2.addColumn("usuario");
        modelo2.addColumn("contraseña");
        modelo2.addColumn("productos");
         modelo2.addColumn("ID");
          modelo2.addColumn("saldo");
          modelo2.addColumn("cuenta");
                  
        jt_clientes.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modifySthis code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JTextField();
        tf_usuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        administrador = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre_pro = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        js_cantidad = new javax.swing.JSpinner();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabla_productos = new javax.swing.JTable();
        agregar_productos = new javax.swing.JButton();
        modificar_productos = new javax.swing.JButton();
        eliminar_productos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_productos = new javax.swing.JList<>();
        tf_saldo_cliente = new javax.swing.JTextField();
        tf_id_cliente = new javax.swing.JTextField();
        tf_usuario_cliente = new javax.swing.JTextField();
        tf_contraseña_cliente = new javax.swing.JTextField();
        tf_nombre_cliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_clientes = new javax.swing.JTable();
        agregar_cliente = new javax.swing.JButton();
        modificar_cliente = new javax.swing.JButton();
        elim_cliente = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tf_cuenta = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cliente1 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        login_1 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jButton1.setText("Iniciar Sesión");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                    .addContainerGap(152, Short.MAX_VALUE)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(101, 101, 101)))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addComponent(jButton1)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(333, Short.MAX_VALUE)))
        );

        jLabel3.setText("Nombre");

        jLabel4.setText("cantidad");

        jLabel5.setText("precio");

        jLabel6.setText("fecha de caducidad");

        js_cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jt_tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cantidad", "nombre", "precio", "fecha"
            }
        ));
        jScrollPane1.setViewportView(jt_tabla_productos);

        agregar_productos.setText("Agregar");
        agregar_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_productosMouseClicked(evt);
            }
        });

        modificar_productos.setText("Modificar");
        modificar_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificar_productosMouseClicked(evt);
            }
        });

        eliminar_productos.setText("eliminar");
        eliminar_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar_productosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jd_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(95, 95, 95)
                                .addComponent(tf_nombre_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(93, 93, 93)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(agregar_productos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modificar_productos)
                .addGap(208, 208, 208)
                .addComponent(eliminar_productos)
                .addGap(192, 192, 192))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombre_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(js_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_productos)
                    .addComponent(modificar_productos)
                    .addComponent(eliminar_productos))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("productos", jPanel1);

        jLabel7.setText("Nombre");

        jLabel8.setText("Usuario");

        jLabel9.setText("Contraseña");

        jLabel10.setText("Productos");

        jLabel11.setText("ID");

        jLabel12.setText("Saldo");

        jl_productos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_productos);

        jt_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Contraseña", "Porductos", "ID", "Saldo", "cuenta"
            }
        ));
        jScrollPane3.setViewportView(jt_clientes);

        agregar_cliente.setText("agregar");
        agregar_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_clienteMouseClicked(evt);
            }
        });

        modificar_cliente.setText("modificar");
        modificar_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificar_clienteMouseClicked(evt);
            }
        });

        elim_cliente.setText("eliminar");
        elim_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elim_clienteMouseClicked(evt);
            }
        });

        jLabel13.setText("Cuenta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(agregar_cliente)
                        .addGap(229, 229, 229)
                        .addComponent(modificar_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(elim_cliente)
                        .addGap(155, 155, 155))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_usuario_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_contraseña_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_saldo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(tf_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(tf_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_usuario_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_contraseña_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_saldo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar_cliente)
                    .addComponent(elim_cliente)
                    .addComponent(agregar_cliente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("cliente", jPanel2);

        javax.swing.GroupLayout administradorLayout = new javax.swing.GroupLayout(administrador.getContentPane());
        administrador.getContentPane().setLayout(administradorLayout);
        administradorLayout.setHorizontalGroup(
            administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        administradorLayout.setVerticalGroup(
            administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout cliente1Layout = new javax.swing.GroupLayout(cliente1.getContentPane());
        cliente1.getContentPane().setLayout(cliente1Layout);
        cliente1Layout.setHorizontalGroup(
            cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        cliente1Layout.setVerticalGroup(
            cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Supermercado");

        login_1.setText("Login");
        login_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_1ActionPerformed(evt);
            }
        });
        jMenu1.add(login_1);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_1ActionPerformed
        // TODO add your handling code here:
          login.setModal(true);
        login.pack();
        login.setLocationRelativeTo(this);
        login.setVisible(true);
    }//GEN-LAST:event_login_1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(tf_usuario.getText().equals(usuario)&&tf_contraseña.getText().equals(contraseña)){
              administrador.setModal(true);
        administrador.pack();
        administrador.setLocationRelativeTo(this);
        administrador.setVisible(true);
         login.setVisible(false);
         login_1.setVisible(false);
         logout.setVisible(true);
         tf_usuario.setText("");
         tf_contraseña.setText("");
         
        }
        for (int i = 0; i < clientes.size(); i++) {
            if((clientes.get(i).getUsuario().equals(usuario))&&clientes.get(i).getContraseña().equals(contraseña)){
                 cliente1.setModal(true);
                cliente1.pack();
                cliente1.setLocationRelativeTo(this);
                cliente1.setVisible(true); 
                login.setVisible(false);
                login_1.setVisible(false);
         logout.setVisible(true);
         tf_usuario.setText("");
         tf_contraseña.setText("");
            }
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void agregar_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_productosMouseClicked
        // TODO add your handling code here:
        Dba db=new Dba("./base1.mdb");
        db.conectar();
        
        try {
            String nombre=tf_nombre_pro.getText();
            int cantidad=Integer.parseInt(js_cantidad.getValue().toString());
            double precio=Double.parseDouble(tf_precio.getText());
            String  fecha_caducidad= jd_fecha.getDate().toString();
            
            java.util.Date fecha= jd_fecha.getDate();
            
           db.query.execute("INSERT INTO tabla_productos (nombre, precio, fecha,cantidad)VALUES('"+nombre+
                   "',"+precio+",'"+fecha_caducidad+"',"+cantidad+")");
           
            productos.add(new productos(cantidad, nombre, precio, fecha));
            System.out.println(productos);
//            Object row1[]={productos.get(cont).getCantidad(),productos.get(cont).getNombre(),productos.get(cont).getPrecio(), productos.get(cont).getFecha()};
//      
//             DefaultTableModel m= (DefaultTableModel)jt_tabla_productos.getModel();
//                    m.addRow(row1);
//                    jt_tabla_productos.setModel(m);
        Object [] newrow= new Object[4];
            newrow[0]=productos.get(cont).getCantidad();
            newrow[1]=productos.get(cont).getNombre();
            newrow[2]=productos.get(cont).getPrecio();
            newrow[3]=productos.get(cont).getFecha();
            modelo.addRow(newrow);
            cont++;
            tf_nombre_pro.setText("");
            tf_precio.setText("");
            
            
            
            DefaultListModel modelo_lista=(DefaultListModel)jl_productos.getModel();
            modelo_lista.addElement(new productos(cantidad, nombre, precio, fecha));
            jl_productos.setModel(modelo_lista);
            
                db.commit();//commit es como el flush
            JOptionPane.showMessageDialog(administrador, "producto agregado");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
        
    }//GEN-LAST:event_agregar_productosMouseClicked

    private void modificar_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_productosMouseClicked
        // TODO add your handling code here:
        
        int x=jt_tabla_productos.getSelectedRow();
        if(x>=0){
            
        
        String nombre=productos.get(x).getNombre();
//        int cantidad=Integer.parseInt(JOptionPane.showInputDialog("nueva cantidad"));
//        String nombre1=JOptionPane.showInputDialog("nuevo nombre");
//        double precio=Double.parseDouble(JOptionPane.showInputDialog("nuevo precio"));
        
        productos product=new productos();
        // tf_nombre_r.setText(tabla_rocoso.getValueAt(filasele, 0).toString());
        
        tf_nombre_pro.setText(jt_tabla_productos.getValueAt(x, 0).toString());
        tf_precio.setText(jt_tabla_productos.getValueAt(x, 2).toString());
        modelo.removeRow(x);
        //tf_nombre_r.setText(tabla_rocoso.getValueAt(filasele, 0).toString());
        
      Dba db=new Dba("./base1.mdb");
        db.conectar();
        
        try {
          
            db.query.execute("update tabla_productos set nombre='"+tf_nombre_pro.getText()+"',cantidad="+Integer.parseInt(jd_fecha.getDate().toString())+",precio='"+Double.parseDouble(tf_precio.getText())+"'where nombre='"+nombre+"'");
            db.commit();
            productos.get(x).setNombre(tf_nombre_pro.getText());
            productos.get(x).setCantidad(Integer.parseInt(jd_fecha.getDate().toString()));
            productos.get(x).setPrecio(Double.parseDouble(tf_precio.getText()));
            
            
            JOptionPane.showMessageDialog(administrador, "producto modificado");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        
        db.desconectar();
       
        }
    }//GEN-LAST:event_modificar_productosMouseClicked

    private void eliminar_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_productosMouseClicked
        // TODO add your handling code here:
        
         int x=jt_tabla_productos.getSelectedRow();
         if(x>=0){
             
         
        String nombre=productos.get(x).getNombre();
         Dba db=new Dba("./base1.mdb");
            db.conectar();

            try {
               db.query.execute("delete from tabla_productos where nombre='"+nombre+"'");
               db.commit();
               modelo.removeRow(x);
               productos.remove(x);
            JOptionPane.showMessageDialog(administrador, "producto eliminado");
            } catch (SQLException e) {
                e.printStackTrace();
            }
            db.desconectar();
         }
    }//GEN-LAST:event_eliminar_productosMouseClicked

    private void agregar_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_clienteMouseClicked
        // TODO add your handling code here:
         Dba db=new Dba("./base1.mdb");
        db.conectar();
         try {
             String cuenta=tf_cuenta.getText();
            String nombre=tf_nombre_cliente.getText();
            String usuario2=tf_usuario_cliente.getText();
            String contra=tf_contraseña_cliente.getText();
            String ID=tf_id_cliente.getText();
            double saldo=Double.parseDouble(tf_saldo_cliente.getText());
           productos pro= productos.get(jl_productos.getSelectedIndex());
           String p=pro.toString();
           
            
            
            
           db.query.execute("INSERT INTO tabla_cliente ( nombre, usuario, contraseña,productos,ID, saldo,cuenta"
                   + ")VALUES('"+nombre+"','"+usuario2+"','"+contra+"','"+p+"','"+ID+"',"+saldo+","+cuenta+")");
           
            clientes.add(new cliente(cuenta, nombre, usuario2, contra, ID, saldo));
            clientes.get(cont1).setProductos(pro);
           
//            
        Object [] newrow2= new Object[7];
            newrow2[0]=clientes.get(cont1).getNombre();
            newrow2[1]=clientes.get(cont1).getUsuario();
            newrow2[2]=clientes.get(cont1).getContraseña();
            newrow2[3]=clientes.get(cont1).getProductos();
            newrow2[4]=clientes.get(cont1).getID();
            newrow2[5]=clientes.get(cont1).getSaldo();
            newrow2[6]=clientes.get(cont1).getCuenta();
            
            modelo2.addRow(newrow2);
            cont1++;
          tf_nombre_cliente.setText("");
          tf_usuario_cliente.setText("");
          tf_contraseña_cliente.setText("");
          tf_cuenta.setText("");
          tf_saldo_cliente.setText("");
          tf_id_cliente.setText("");
            
            
          
            
                db.commit();//commit es como el flush
            JOptionPane.showMessageDialog(administrador, "producto agregado");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
        
    }//GEN-LAST:event_agregar_clienteMouseClicked

    private void modificar_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_clienteMouseClicked
        // TODO add your handling code here:
        int x=jt_clientes.getSelectedRow();
        if(x>=0){
            
        
        String nombre=clientes.get(x).getNombre();
        
        tf_nombre_cliente.setText(jt_clientes.getValueAt(x, 0).toString());
        tf_usuario_cliente.setText(jt_clientes.getValueAt(x, 1).toString());
        tf_contraseña_cliente.setText(jt_clientes.getValueAt(x, 2).toString());
        
        tf_id_cliente.setText(jt_clientes.getValueAt(x, 4).toString());
        tf_saldo_cliente.setText(jt_clientes.getValueAt(x, 5).toString());
        tf_cuenta.setText(jt_clientes.getValueAt(x, 6).toString());
         productos pro= productos.get(jl_productos.getSelectedIndex());
           String p=pro.toString();
        modelo2.removeRow(x);
        //tf_nombre_r.setText(tabla_rocoso.getValueAt(filasele, 0).toString());
        
      Dba db=new Dba("./base1.mdb");
        db.conectar();
        
        try {
          
            db.query.execute("update tabla_cliente set nombre='"+tf_nombre_cliente.getText() +"',usuario='"+tf_usuario_cliente.getText()+"'"
                    + ",productos='"+p+"',ID='"+tf_saldo_cliente+"',cuenta='"+tf_cuenta.getText()+"'where nombre='"+nombre+"'");
            db.commit();
            
           clientes.get(x).setNombre(tf_nombre_cliente.getText());
            clientes.get(x).setUsuario(tf_usuario_cliente.getText());
             clientes.get(x).setContraseña(tf_contraseña_cliente.getText());
              clientes.get(x).setCuenta(tf_cuenta.getText());
              
              clientes.get(x).setID(tf_id_cliente.getText());
               clientes.get(x).setSaldo(Double.parseDouble(tf_saldo_cliente.getText()));
            
            
            JOptionPane.showMessageDialog(administrador, "cliente modificado");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        
        db.desconectar();
        }
    }//GEN-LAST:event_modificar_clienteMouseClicked

    private void elim_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elim_clienteMouseClicked
        // TODO add your handling code here:
         int x=jt_clientes.getSelectedRow();
         if(x>0){
             
         
        String nombre=clientes.get(x).getNombre();
         Dba db=new Dba("./base1.mdb");
            db.conectar();

            try {
               db.query.execute("delete from tabla_cliente where nombre='"+nombre+"'");
               db.commit();
               modelo2.removeRow(x);
               clientes.remove(x);
            JOptionPane.showMessageDialog(administrador, "cliente eliminado");
            } catch (SQLException e) {
                e.printStackTrace();
            }
            db.desconectar();
         }
    }//GEN-LAST:event_elim_clienteMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login_1.setVisible(true);
        administrador.setVisible(false);
        cliente1.setVisible(false);
        logout.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog administrador;
    private javax.swing.JButton agregar_cliente;
    private javax.swing.JButton agregar_productos;
    private javax.swing.JDialog cliente1;
    private javax.swing.JButton elim_cliente;
    private javax.swing.JButton eliminar_productos;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private javax.swing.JList<String> jl_productos;
    private javax.swing.JSpinner js_cantidad;
    private javax.swing.JTable jt_clientes;
    private javax.swing.JTable jt_tabla_productos;
    private javax.swing.JDialog login;
    private javax.swing.JMenuItem login_1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JButton modificar_cliente;
    private javax.swing.JButton modificar_productos;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_contraseña_cliente;
    private javax.swing.JTextField tf_cuenta;
    private javax.swing.JTextField tf_id_cliente;
    private javax.swing.JTextField tf_nombre_cliente;
    private javax.swing.JTextField tf_nombre_pro;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_saldo_cliente;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuario_cliente;
    // End of variables declaration//GEN-END:variables
String usuario="erick123";
String contraseña="321kcire";
ArrayList<productos> productos=new ArrayList();
ArrayList<cliente> clientes=new ArrayList();
cliente cliente=new cliente();


int cont1=0;
int cont=0;
}
